// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bmyjzpulpksualuzqtwd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJteWp6cHVscGtzdWFsdXpxdHdkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQwMzc0OTksImV4cCI6MjA0OTYxMzQ5OX0.eQcbfPyTk8fSejmOYAOR1z6EBubWhN2gH4Ivv1RVAdI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);